{% set name = "echemdb" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/echemdb-{{ version }}.tar.gz
  sha256: 18bb3072912d2a8b726405cf58169a18668d4aad12d0c105c0fa276706c3c1a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - astropy >=5,<6
    - filelock >=3,<4
    - frictionless >=4.29,<5
    - matplotlib-base >=3.5.0,<4
    - pandas >=1,<2
    - plotly >=5,<6
    - pybtex >=0.24,<0.25
    - python >=3.9

test:
  imports:
    - echemdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/echemdb/
  summary: A Python library to interact and work with the echemdb repository.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://echemdb.github.io/echemdb/
  dev_url: https://github.com/echemdb/echemdb

extra:
  recipe-maintainers:
    - DunklesArchipel
    - linuxrider
    - nicohoermann
    - saraedum
